### ISSUE TITLE
google auth needs GOOGLE_CLIENT_ID not GOOGLE_CLIENT_KEY

### ISSUE THREAD

**Issue by euri10** [authlib/playground#1]
I tried to run a simple oauth2 flask authentication with google, using part of the connect route that is shown here.

it failed miserably using v0.6 of authlib because I was using GOOGLE_CLIENT_KEY as per the [dev.config.py.sample](https://github.com/authlib/playground/blob/master/conf/)

changing it to GOOGLE_CLIENT_ID solves the issue

I'm not sure it's an issue in playground as it seems it uses version 0.5 and things might have changed between versions, but it was confusing enough I let you know !

**Comment by lepture** [comment]
Check requirements.txt

Playground is not ready for Authlib 0.6
